import "../globals.css";
import { SanityLive } from "@/sanity/lib/live";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        {children}
        <SanityLive></SanityLive>
      </body>
    </html>
  );
}
